

int main()
try{
	return 0;
}
catch (exception& e) {
	return 1;
}
catch (...) {
	return 2;
}